appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: hAzSw4MJVtQqADEPVG3u9v1upngHrWi3tjJEBlmNU4j/hv6NScuKF1ixrPFuGLyWSUOlTFLPU+sPbySH+ylmZkudrkRTJR0lVAm6nM3FB+/BDJCp3fbMIzhIoprvC4NO7BvyjJCz19v2tLnVy54ihaA8YJd7uE2qIRcaSN85vWAQjGsOypkINOZiULcQYxT1x9LquPG0KqvtIbQNsCRJ0PKxlN1Pi+dL1NRyE9+TEpflok2R9pVr8PZMf/5j//cPkuBlOZhIQTXn9ZdP4P0Z15I9aJrOdbOmjN9RssSZBNZiirzMsz+jLcWW32In625yxLqzIm/lvJ4ocwIPrzK2HZ/33M0quQTjxgNPgeMbBpau3LB1aCKGs1MQtD4xqfxCk/nPwv6g/3kSLe6LmnzKfssS82t3zFsDwN86BA9Tz7no9btordSn/eAnBjm7vE0uVTBSqZLcrxt2d8SxF2W8xlorYWpqZcaRsuCs7q3jBCaGV3SCHSfED+/cVB7u8WONPz9qQ5HE/Lhik+qbcqtVcE/L5nM3m1yqRLRwd03PKm6Mn97MHZ1xP0qXB1u8hZYH/8r1U3q2hN2dyhHEMrHOAUwm1phFTKMbmKy3kq1KS28uidN7wFnNZnu8n73gxBl9sJUam438wc/9enll/bnySzlCKbuX5dHJ6FpslvkcabM=}
provider:
  win: azure
conda_forge_output_validation: true
