travis:
  secure:
    BINSTAR_TOKEN: iEdmiGsp9kRivzCeiEmEmGxFGBhHJwv+VbQt9X34Hytkpr+5vMcXMq0FKKAbZNt3k3h8CtaJ8xN0ZWDm4vLz5AE8kyrJIgIgIgjALR/ouaQlwUUkx4NDEBEzQBMPMwXqsHdq14GRRLr8260NCNo0MXyly+fFoAYBuZRuB4VIYw+3hr8VNJtNsYtP2UcCdlxdUEbyodhSA+E/fi9eRUOc/rlG78IhrpAg+NStP2ZtHvvzHPja/8PlNkAuHjf2N0sDgfGn8s+gOTKzqYXymE5FC3f/A9fWkupLvSj+vE7RGkfUEi0stG9tUZHVKX28OQZB4I529dvj8K5Sjr48cywooCKitD2xNL9MhC+IB6mvQPSvLgqpHvq6wGxuMfm07Hx3XxnaZj0hzPFdWDOt7+rPNN6OBi0piCxTwFV0Wv0tvfLlvxjT/7ZBLP4Hqm1ImEdao14pnlQeUAZJCeZ2uPxvAS1rNJBx4CE9zTeIofL+bGpm8lG7NHDc+YZgSuqsJ7ckopH5ey7bSPV/+pBJuJlmogmUgOGwvK/C3JrxJzHjKO6uHd1OgyIfy2a9uxvGhWVf7LFgOEbb1XpUwxnUHq5YvznQ6EBXTBPOIwoczQRyDNZAXHTVJJ1DJkDP9VMGctY+U5nn3B3klvZ6f3Ql6zaM7bW63OnCy2MM/OS2IpF77gU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
